export type PlatformEventTypes =
    "shell.runProcess"
    | "shell.runProcessInShell"
    | "shell.showModal"
    | "shell.openModal"
    | "shell.begin"
    | "shell.progress"
    | "shell.done"
    | "shell.refresh"
    | "shell.navigateTo"
    | "shell.authenticated"
    | "shell.loggedOut"
    | "shell.gotProfile"
    | "shell.showNotification"
    | "shell.closeModal"
    | "shell.processStarted"
    | "shell.dappLoading"
    | "shell.dappLoaded"
    | "shell.modalChanged"
    | "shell.routeChanged"
    | "shell.navigation.left.click"
    | "shell.navigation.right.click"
    | "shell.navigation.center.left.click"
    | "shell.navigation.center.main.click"
    | "shell.navigation.center.right.click"

    | "circles.web3providerChanged"

    | "process.ready"
    | "process.nop"
    | "process.back"
    | "process.skip"
    | "process.shellEvent"
    | "process.requestShellEvent"
    | "process.continue"
    | "process.triggerSelf"
    | "process.cancel"
    | "process.cancelRequest"
    | "process.prompt"
    | "process.error"
    | "process.success"
    | "process.repeat"
    | "process.stopped"
    | "blockchain"
    | "signal.begin"
    | "signal.progress"
    | "signal.ready"
    | "signal.unavailable"

    //
    // IPC
    | "process.ipc.bubble" // used with 'sendParent' to bubble events up to the top
    | "process.ipc.sinker" // used with 'send' to sink down a result for a previously bubbled event

